version: '3'
services:
  postgres:
    image: postgres:12.4
    container_name: portfolio-db
    networks:
      - default
    env_file:
      - db.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  portfolio:
    container_name: portfolio-server
    networks:
      - default
    depends_on:
      - postgres
    env_file:
      - email.env
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./key.json:/app/key.json
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/portfolio-db

volumes:
  postgres-data:
