version: '3'
services:
  portfolio:
    container_name: portfolio-client
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        EMAIL_API_KEY: ${EMAIL_API_KEY}
        EMAIL_SENDER_NAME: ${EMAIL_SENDER_NAME}
        EMAIL_SENDER_ADDRESS: ${EMAIL_SENDER_ADDRESS}
        EMAIL_RECIPIENT_NAME: ${EMAIL_RECIPIENT_NAME}
        EMAIL_RECIPIENT_ADDRESS: ${EMAIL_RECIPIENT_ADDRESS}
    ports:
      - 8080:8080