version: '3'
services:
  postgres:
    image: postgres:12.4
    container_name: portfolio-db
    env_file:
      - db.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  portfolio:
    container_name: portfolio-server
    depends_on:
      - postgres
    env_file:
      - email.env
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker-compose

volumes:
  postgres-data:
