version: '3'
services:
  portfolio-db:
    container_name: portfolio-db
    image: postgres:12.4
    networks:
      portfolio:
        aliases:
          - portfolio-db-postgresql
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/
  portfolio-server:
    container_name: portfolio-server
    networks:
      portfolio:
        aliases:
          - portfolio-server-service
    depends_on:
      - portfolio-db
    env_file:
      - .env
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile

networks:
  portfolio:

volumes:
  postgres-data:
