spring:
  session:
    store-type: redis
    redis:
      flush-mode: immediate
      namespace: portfolio:session
  application.name: portfolio-server
  main.banner-mode: off
  output.ansi.enabled: always
  flyway.clean-on-validation-error: true
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/portfolio

management:
  endpoint.health:
    enabled: true
    show-details: always
  auditevents.enabled: true
  endpoints.web.exposure.include: '*'
server:
  http2.enabled: true
  compression.enabled: true
email:
  api-key: mock-api-key
  sender:
    name: Portfolio Inquiry
    address: sender@mock-domain.com
  recipient:
    name: Philip N. Ossem
    address: recipient@mock-domain.com
security:
  chat-session-id: admin-session
  admin:
    uid: admin
    password: admin
    username: admin
  system:
    uid: system
    password: system
    username: system
