spring:
  application.name: portfolio-server
  main.banner-mode: off
  output.ansi.enabled: always
management:
  endpoint.health:
    enabled: true
    show-details: always
  auditevents.enabled: true
  endpoints.web.exposure.include: '*'
server:
  http2.enabled: true
  compression.enabled: true

rabbit:
  key: chat.key
  queue: chat.queue
  exchange: chat.exchange

email:
  address: frank@em6169.mitch.engineering