spring:
  application.name: portfolio-server
  main.banner-mode: off
  output.ansi.enabled: always
management:
  endpoint.health:
    enabled: true
    show-details: always
  auditevents.enabled: true
  endpoints.web.exposure.include: '*'
server:
  http2.enabled: true
  compression.enabled: true

