apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: portfolio-server-autoscaler
  namespace: portfolio
  labels:
    app: portfolio-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: portfolio-server
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80